<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="1" total="6" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-07-11T13:02:57 IST" name="Suite" finished-at="2024-07-11T13:03:16 IST" duration-ms="18743">
    <groups>
    </groups>
    <test started-at="2024-07-11T13:02:57 IST" name="Login Validation Test" finished-at="2024-07-11T13:03:16 IST" duration-ms="18743">
      <class name="ecommerceproject.FrameworkPackage.Tests.LoginValidationTest">
        <test-method is-config="true" signature="lunchApplication()[pri:0, instance:ecommerceproject.FrameworkPackage.Tests.LoginValidationTest@36804139]" started-at="2024-07-11T13:02:57 IST" name="lunchApplication" finished-at="2024-07-11T13:03:02 IST" duration-ms="5112" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- lunchApplication -->
        <test-method signature="loginValidationWithCorrectEmailAndPassword()[pri:0, instance:ecommerceproject.FrameworkPackage.Tests.LoginValidationTest@36804139]" started-at="2024-07-11T13:03:02 IST" name="loginValidationWithCorrectEmailAndPassword" finished-at="2024-07-11T13:03:04 IST" duration-ms="1455" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginValidationWithCorrectEmailAndPassword -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:ecommerceproject.FrameworkPackage.Tests.LoginValidationTest@36804139]" started-at="2024-07-11T13:03:04 IST" name="tearDown" finished-at="2024-07-11T13:03:04 IST" duration-ms="423" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="lunchApplication()[pri:0, instance:ecommerceproject.FrameworkPackage.Tests.LoginValidationTest@36804139]" started-at="2024-07-11T13:03:04 IST" name="lunchApplication" finished-at="2024-07-11T13:03:06 IST" duration-ms="1607" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- lunchApplication -->
        <test-method retried="true" signature="loginValidationWithWrongEmail()[pri:0, instance:ecommerceproject.FrameworkPackage.Tests.LoginValidationTest@36804139]" started-at="2024-07-11T13:03:06 IST" name="loginValidationWithWrongEmail" finished-at="2024-07-11T13:03:07 IST" duration-ms="793" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [*Enter Valid Email] but found [*Enter Validy Email]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [*Enter Valid Email] but found [*Enter Validy Email]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at ecommerceproject.FrameworkPackage.Tests.LoginValidationTest.loginValidationWithWrongEmail(LoginValidationTest.java:19)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginValidationWithWrongEmail -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:ecommerceproject.FrameworkPackage.Tests.LoginValidationTest@36804139]" started-at="2024-07-11T13:03:07 IST" name="tearDown" finished-at="2024-07-11T13:03:07 IST" duration-ms="256" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="lunchApplication()[pri:0, instance:ecommerceproject.FrameworkPackage.Tests.LoginValidationTest@36804139]" started-at="2024-07-11T13:03:07 IST" name="lunchApplication" finished-at="2024-07-11T13:03:09 IST" duration-ms="1708" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- lunchApplication -->
        <test-method signature="loginValidationWithWrongEmail()[pri:0, instance:ecommerceproject.FrameworkPackage.Tests.LoginValidationTest@36804139]" started-at="2024-07-11T13:03:09 IST" name="loginValidationWithWrongEmail" finished-at="2024-07-11T13:03:09 IST" duration-ms="511" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [*Enter Valid Email] but found [*Enter Validy Email]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [*Enter Valid Email] but found [*Enter Validy Email]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at ecommerceproject.FrameworkPackage.Tests.LoginValidationTest.loginValidationWithWrongEmail(LoginValidationTest.java:19)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginValidationWithWrongEmail -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:ecommerceproject.FrameworkPackage.Tests.LoginValidationTest@36804139]" started-at="2024-07-11T13:03:09 IST" name="tearDown" finished-at="2024-07-11T13:03:10 IST" duration-ms="278" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="lunchApplication()[pri:0, instance:ecommerceproject.FrameworkPackage.Tests.LoginValidationTest@36804139]" started-at="2024-07-11T13:03:10 IST" name="lunchApplication" finished-at="2024-07-11T13:03:11 IST" duration-ms="1592" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- lunchApplication -->
        <test-method signature="loginValidationWithWrongEmailAndPassword()[pri:0, instance:ecommerceproject.FrameworkPackage.Tests.LoginValidationTest@36804139]" started-at="2024-07-11T13:03:11 IST" name="loginValidationWithWrongEmailAndPassword" finished-at="2024-07-11T13:03:13 IST" duration-ms="1211" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginValidationWithWrongEmailAndPassword -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:ecommerceproject.FrameworkPackage.Tests.LoginValidationTest@36804139]" started-at="2024-07-11T13:03:13 IST" name="tearDown" finished-at="2024-07-11T13:03:13 IST" duration-ms="259" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="lunchApplication()[pri:0, instance:ecommerceproject.FrameworkPackage.Tests.LoginValidationTest@36804139]" started-at="2024-07-11T13:03:13 IST" name="lunchApplication" finished-at="2024-07-11T13:03:14 IST" duration-ms="1591" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- lunchApplication -->
        <test-method signature="loginValidationWithWrongPassword()[pri:0, instance:ecommerceproject.FrameworkPackage.Tests.LoginValidationTest@36804139]" started-at="2024-07-11T13:03:14 IST" name="loginValidationWithWrongPassword" finished-at="2024-07-11T13:03:16 IST" duration-ms="1394" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginValidationWithWrongPassword -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:ecommerceproject.FrameworkPackage.Tests.LoginValidationTest@36804139]" started-at="2024-07-11T13:03:16 IST" name="tearDown" finished-at="2024-07-11T13:03:16 IST" duration-ms="252" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- ecommerceproject.FrameworkPackage.Tests.LoginValidationTest -->
    </test> <!-- Login Validation Test -->
  </suite> <!-- Suite -->
</testng-results>
